### ISSUE TITLE
Slow to launch in Windows startup--- feature request?

### ISSUE THREAD

**Issue by rachelsdurden** [complexlogic/flex-launcher#15]
Okay so I'm trying to increase the speed at which the program launches so that it goes immediately to flexlauncher without displaying the desktop for very long. Unfortunately as much as I've tried to lobotomize my startup process and delay tasks with Task Scheduler, I cannot persuade Flex Launcher to start sooner than five seconds.

EXCEPT when I change the windows shell from explorer.exe to Flex Launcher. Doing that causes some weirdness like icons not loading and also a lot of undesirable things behind the scenes. gpedit.msc > Administrative templates > System > Custom User Interface

My feature request is this: Add a config section to auto-run a :fork command whenever you enter a menu. This way, I can launch explorer.exe whenever flex-launcher has started up. It's silly, I know, but I must achieve HTPC perfection!

**Comment by complexlogic** [comment]
I've been considering adding an autostart feature for a while, which would execute a user-supplied command immediately after Flex Launcher starts. Typically this would be used to immediately launch into an application before seeing the launcher, however, in combo with a `:fork` command you could also use it to start `explorer.exe`. This command would be executed one time only, not whenever a menu is entered. Would this work for you?

**Comment by complexlogic** [comment]
I did a bit of experimentation with your proposed setup. The issue with the icons not loading is due to the relative paths in the config file. Normally, when a Windows application is started, the working directory will be the directory that contains its .exe file, so that was how the default config was written. However, when Flex Launcher is run directly via Custom User Interface, that is no longer the case. All you have to do is change the paths in your config file from relative to absolute, and the launcher will behave correctly.

Could you elaborate on what other issues you were experiencing with this setup? I tested it with Kodi, Plex HTPC, Steam Big Picture, and Google Chrome, and everything seems to be working perfectly.

**Comment by rachelsdurden** [comment]
That should work. I'm not 100%, but it's the best chance I have.

**Comment by complexlogic** [comment]
In the latest release, [v1.7](https://github.com/complexlogic/flex-launcher/releases/tag/v1.7), I added two new settings `StartupCmd` and `QuitCmd`, which will execute a user-supplied command when the launcher starts and quits, respectively. I also wrote up [some new documentation on my recommended setup for Windows](https://complexlogic.github.io/flex-launcher/setup_windows#kiosk-mode-setup), which may interested you.

Good luck on your quest for HTPC perfection. I've been trying for a few years, but I've yet to achieve it yet :wink:
