### ISSUE TITLE
OnLaunch=Hide minimizes and doesn't re-appear when used with folder

### ISSUE THREAD

**Issue by ams3401** [complexlogic/flex-launcher#21]
So this is another issue that I discovered in addition to the [previous issue](https://github.com/complexlogic/flex-launcher/issues/20).

`Entry=PC;.\assets\icons\pc.png;"shell:MyComputerFolder"`

Basically, the folder opens just fine inside the launcher, but when I close that folder, Flex Launcher does not re-appear although it shows that it's still running in the Task Manager.

I thought it would be convenient to have access to "This PC" within the launcher so I can connect external drives to HTPC.

Thanks.

**Comment by complexlogic** [comment]
The root cause is basically the same as the browser issue, and I can add another workaround for it. Download the test build [here](https://github.com/complexlogic/flex-launcher/files/9796044/flex-launcher-1.8-modified2win64.zip). Change your menu entry to explicitly invoke `explorer.exe` and pass the folder as an argument, e.g.:
```
Entry=PC;.\assets\icons\pc.png;explorer.exe shell:MyComputerFolder
```

Similar to the browser workaround, the launcher window won't return until *all* Explorer windows have been closed (not just the one the launcher opened). This means that you shouldn't have any Explorer windows open prior to running the launcher. This limitation shouldn't be a problem in a typical HTPC setup where the launcher is run via autostart or a shortcut, but keep it in mind when running it during testing/setup.

Let me know if that works for you.

**Comment by ams3401** [comment]
> Let me know if that works for you.

Works fantastic! Thank you very much.
