### ISSUE TITLE
 accidental usage of  mouse pointer 

### ISSUE THREAD

**Issue by krish1997-lab** [complexlogic/flex-launcher#4]
whenever there is accidental usage of  mouse pointer  the PC remote or gamepad's   enter button won't work  in flex launcher

**Comment by complexlogic** [comment]
I need more information so I can reproduce this issue.

1. Which operating system are you using?
2. What do you mean by "usage" of mouse pointer? When you move the mouse? When you click a button? If a button, which button?
3. Only the enter button stops working, or all buttons stop working?

Please give me as many details about your setup and what causes the issue as you can think of.

**Comment by krish1997-lab** [comment]
1.OS- Windows 11
2.whenever i accidently use gyroscopic mouse in HTPC remote the enter button does not function
3.yes only enter button

**Comment by complexlogic** [comment]
Do left and right still work on the gamepad too?

**Comment by krish1997-lab** [comment]
> Do left and right still work on the gamepad too?

Yes it works only enter button won't works

**Comment by complexlogic** [comment]
Ok. When this issue happens, does enter still work to open a submenu? For example, the default configuration has "System" submenu. Try to open a submenu and see if enter works in that case. Please try with both remote and gamepad.

**Comment by Kubusky** [comment]
The enter/ok button on gyro mouse HTPC remote works actually as mouse left click button when the "gyro mode" is activated, on "standard mode" (gyro mouse disabled) - the enter/ok button on HTPC remote works as standard keyboard enter button. Flex launcher does not support mouse controls nor binding left mouse click as special (enter) key in config, that's why it won't work.
Is some sort of mouse support planned? I use my HTPC in gyro mouse mode most of the time and I also have this issue. Basic left mouse click as enter would be enough. Thank you.

**Comment by complexlogic** [comment]
@Kubusky Thanks for the explanation, that helps a lot.
> Basic left mouse click as enter would be enough.

This would be relatively easy to implement. I will have a setting for it in the next release.

**Comment by complexlogic** [comment]
@krish1997-lab @Kubusky In the latest release, [v1.5](https://github.com/complexlogic/flex-launcher/releases/tag/v1.5), I have added a setting for you called ```MouseSelect```. When enabled, it allows the user to select the highlighted entry using the mouse left click. It's disabled by default, so you will need to enable it in your config file. See the updated [configuration file documentation](https://github.com/complexlogic/flex-launcher/blob/master/extra/docs/configuration.md) for more information.
