### ISSUE TITLE
Performance hit when gamepad support is enabled and Flex-Launcher is not hidden.

### ISSUE THREAD

**Issue by zpaolo11x** [complexlogic/flex-launcher#9]
I'm on Ubuntu 22.04, I use Flex-Launcher as a frontend to run emulators and media players. I have a bluetooth connected 8BitDo Lite gamepad to control FL. I noticed this: if in the options I set OnLaunch to "None", the performance of the emulator frontend is reduced, it gets back to normal when I "kill" flex-launcher or if I set OnLaunch to "Hide". It seems it's related to the gamepad support because, with the gamepad turned off, everything runs normal.

**Comment by complexlogic** [comment]
Is your Ubuntu desktop running Wayland? If so, is Flex Launcher running in XWayland compatibility mode? Generally it will unless you pass `SDL_VIDEODRIVER=wayland` environment variable.

**Comment by zpaolo11x** [comment]
No, I'm running X11 because, well I don't remember why, I'm just more familiar with that. I just checked and loginctl confirmed that I'm under x11, not wayland

**Comment by complexlogic** [comment]
I am a bit puzzled as to why the gamepad is affecting the performance, since the gamepad isn't polled when the application is running. 

I uploaded a test branch `gamepad` with a simple change that disconnects the gamepad prior to application launch, then automatically reconnects it after the application closes. Please clone the branch
```
git clone -b gamepad https://github.com/complexlogic/flex-launcher.git
```
Then build according to the [instructions](https://github.com/complexlogic/flex-launcher/blob/master/docs/compilation.md#linux), run it with OnLaunch set to None and the gamepad connected. See if that fixes the performance problem in your applications.

**Comment by zpaolo11x** [comment]
Well with this build it works perfectly!

**Comment by complexlogic** [comment]
Great. I'm not really sure why it fixes the problem. But I was already thinking of making this change anyway to account for the case where the user switches to a different gamepad device while the application is running, so I'm going to go ahead and merge this into `master`.

**Comment by complexlogic** [comment]
I just discovered there was a minor bug in that `gamepad` branch. Could you run `git pull` and then build and try one more time before I merge it? Thanks.

**Comment by zpaolo11x** [comment]
Sorry for the late reply, I just pulled and build again and it seems to work fine for me.
